name: open_file_transfer_mobile
description: OpenFileTransfer mobile client.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  grpc: ^4.1.0
  protobuf: ^4.2.0
  file_picker: ^10.3.3
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

